### 01 서울시 구별 CCTV 현황 분석
[학습목표]

- 서울시 각 구별 CCTV 수를 파악하고, 인구대비 CCTV 비율을 파악해서 순위 비교
- 인구대비 CCTV의 평균치를 확인하고, CCTV가 과하게 부족한 구를 확인
- pandas 사용법과 시각화(matplotlib) 사용법을 배운다


#### 판다스 라이브러리 

- 판다스 : python의 데이터 분석 및 조작을 위한 라이브러리
- 표(데이터프레임)형식 데이터를 다루는 강력한 기능 제공
- 엑셀, SQL, CSV 등의 데이터를 불러와 정리, 분석, 변환, 저장하는 기능
- 데이터 분석에 필요적인 라이브러리다


1. pandas 핵심 구조
- pandas에는 Series와 DataFrame 두가지 주요 데이터 구조가 있다

1.1 Series (1차원 데이터 처리시 사용)
- 단일 컬럼 형태의 데이터 구조를 가지고 있다 (시리즈로 컬럼단위 처리)
- 리스트(list)나 배열(array)과 유사하고 인덱스를 사용한다 (인덱싱, 슬라이싱 가능)

1.2 DataFrame (2차원 데이터 처리시 사용)
- 엑셀의 표와 같은 행(row)-열(column) 구조
- 여러 개의 Series(컬럼)으로 구성된 것이다


#### 1. Series attribute (변수)
- index: 인덱스로 저장 (array)
- values : 값 저장 (array)
- dtype : 데이터 타입 저장
- name : series object 이름 -> 데이터프레임으로 가면 컬렴명으로 사용한다

2. Series 데이터 타입 
- index, value 다 array 형식으로 저장
- array 형식 : 넘파이 저장
    - 동일 데이터 타입만 저장 가능
    - 데이터 타입 세분화 된다
     - 정수, 실수, 문자열 등등 다 별도의 데이터 타입 있다
    

In [83]:
# 예제 1 : Series 생성
import pandas as pd #별칭 (외부모듈은 import를 해준다)
# data 에 들어갈 수 있는 것 : 리스트, 딕셔너리, 배열 가능능
data = [1,2,3,4]
series = pd.Series(data)
print(series) 
print(series.index) 
print(series.values) 
print(type(series.values))

series.name = '컬럼명'
print(series.name)


0    1
1    2
2    3
3    4
dtype: int64
RangeIndex(start=0, stop=4, step=1)
[1 2 3 4]
<class 'numpy.ndarray'>
컬럼명


In [84]:
# 2. 데이터프레임 생성
# 딕셔너리로 생성
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['Seoul', 'Busan', 'Incheon']
}
# print(data)
df = pd.DataFrame(data)
print(df)

      Name  Age     City
0    Alice   25    Seoul
1      Bob   30    Busan
2  Charlie   35  Incheon


In [85]:
# 특정 컬럼 선택
# 컬럼들 확인
print(df.columns)

print(df['Name'])
print(df['Age'])

Index(['Name', 'Age', 'City'], dtype='object')
0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object
0    25
1    30
2    35
Name: Age, dtype: int64


In [86]:
# DataFrame 주요 속성(attribute)
# 1. columns : 컬럼들을 관리
# 2. index : 인덱스 관리
# 3. dtype : 컬럼별 데이터 타입 관리
# 4. shape : 데이터 구조 (행x열)
print(df.columns) #dtype 이 object 는 문자열이다
print(df.index)
print(df.values) #값만 뽑기
print(type(df.values)) # array -> numpy 전용 데이터 저장 방법
print(df.shape) #(3,3)->tuple형태


Index(['Name', 'Age', 'City'], dtype='object')
RangeIndex(start=0, stop=3, step=1)
[['Alice' 25 'Seoul']
 ['Bob' 30 'Busan']
 ['Charlie' 35 'Incheon']]
<class 'numpy.ndarray'>
(3, 3)


In [87]:
# CCTV 현황 데이터 읽기 
# 파일: data_collection\data\02 자료실\01. CCTV_in_Seoul.csv//data_collection
# csv 읽기 함수 : pd.read_csv() => return DataFrame object
import pandas as pd
import numpy as np

CCTV_Seoul = pd.read_csv(
    './data/data/01. CCTV_in_Seoul.csv', #파일과 파일의 경로를 지정
    encoding='utf-8'                     #한글을 유니코드를 사용해서 읽기
)
# print(type(CCTV_Seoul))
# print(CCTV_Seoul) # 전체 데이터 확인 할때 사용
# print(CCTV_Seoul.head()) #상위5개 확인할때
# print(CCTV_Seoul.tail()) #하위5개 확인시 사용
# CCTV_Seoul.head() # print 하면 문자열로 바꿔서 출력해줌,
CCTV_Seoul.head(10) #상위 10개 행 데이터 추출=>DataFrame return




기관명    소계  2013년도 이전  2014년  2015년  2016년
0  강남구  2780       1292    430    584    932
1  강동구   773        379     99    155    377
2  강북구   748        369    120    138    204
3  강서구   884        388    258    184     81
4  관악구  1496        846    260    390    613
5  광진구   707        573     78     53    174
6  구로구  1561       1142    173    246    323
7  금천구  1015        674     51    269    354
8  노원구  1265        542     57    451    516
9  도봉구   485        238    159     42    386

In [88]:
# CCTV_Seoul DataFrame 구조 확인 
# 행정보 추출
# CCTV_Seoul.index : RangeIndex(start=0, stop=25, step=1): 정수인덱스
print(CCTV_Seoul.columns)
# 2.1 특정 컬럼 추출
print(CCTV_Seoul.columns[0])
print(CCTV_Seoul.columns[-1])
# 3. 구조 추출
print(CCTV_Seoul.shape) # (25, 6) : 25행, 6개 컬럼-> tuple-> index존재
print(CCTV_Seoul.shape[0]) #데이터 개수 확인
print(CCTV_Seoul.shape[1]) #컬럼 개수 확인





Index(['기관명', '소계', '2013년도 이전', '2014년', '2015년', '2016년'], dtype='object')
기관명
2016년
(25, 6)
25
6


In [89]:
# 수치 데이터에 기본 통계량을 확인 
# CCTV_Seoul.head(2)
CCTV_Seoul['기관명'] #컬럼추출 -> Series object -> dtype
CCTV_Seoul['소계'].dtype #컬럼추출 -> Series object -> dtype
CCTV_Seoul[['소계', '2014년']] #원하는 컬럼만 추출 가능
CCTV_Seoul['기관명'].dtype #문자열
CCTV_Seoul.columns
CCTV_Seoul.describe()['소계'] #수치데이터 -> 기본통계량 #return DataFrame
CCTV_Seoul.describe() #수치데이터 -> 기본통계량 #return DataFrame


소계    2013년도 이전       2014년       2015년       2016년
count    25.000000    25.000000   25.000000   25.000000   25.000000
mean   1179.080000   764.760000  159.480000  205.200000  385.880000
std     556.728983   415.510257  104.132976  137.877059  182.479981
min     485.000000   238.000000   21.000000   30.000000   81.000000
25%     748.000000   464.000000   78.000000  103.000000  292.000000
50%    1015.000000   573.000000  142.000000  184.000000  377.000000
75%    1496.000000  1070.000000  218.000000  269.000000  467.000000
max    2780.000000  1843.000000  430.000000  584.000000  932.000000

In [90]:
# 데이터 전체 구조 확인(DataFrame)하는 메소드 : info()
CCTV_Seoul.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   기관명        25 non-null     object
 1   소계         25 non-null     int64 
 2   2013년도 이전  25 non-null     int64 
 3   2014년      25 non-null     int64 
 4   2015년      25 non-null     int64 
 5   2016년      25 non-null     int64 
dtypes: int64(5), object(1)
memory usage: 1.3+ KB


In [91]:
# 컬럼명 수정 : 기관명 => 구별 
# 메소드 -> 오브젝트 안에 들어가 있음, 메소드: rename()
#  CCTV_Seoul.columns[0] -> '기관명'
gu = {
    CCTV_Seoul.columns[0] : '구별'
}

CCTV_Seoul.rename(
    columns=gu
) # 복사본에 처리리


구별    소계  2013년도 이전  2014년  2015년  2016년
0    강남구  2780       1292    430    584    932
1    강동구   773        379     99    155    377
2    강북구   748        369    120    138    204
3    강서구   884        388    258    184     81
4    관악구  1496        846    260    390    613
5    광진구   707        573     78     53    174
6    구로구  1561       1142    173    246    323
7    금천구  1015        674     51    269    354
8    노원구  1265        542     57    451    516
9    도봉구   485        238    159     42    386
10  동대문구  1294       1070     23    198    579
11   동작구  1091        544    341    103    314
12   마포구   574        314    118    169    379
13  서대문구   962        844     50     68    292
14   서초구  1930       1406    157    336    398
15   성동구  1062        730     91    241    265
16   성북구  1464       1009     78    360    204
17   송파구   618        529     21     68    463
18   양천구  2034       1843    142     30    467
19  영등포구   904        495    214    195    373
20   용산구  1624       1368    218    112    398
21   은평구  1873       1138    224    278    468
22   종로구  1002        464    314    211    630
23    중구   671        413    190     72    348
24   중랑구   660        509    121    177    109

In [92]:
CCTV_Seoul.head()

기관명    소계  2013년도 이전  2014년  2015년  2016년
0  강남구  2780       1292    430    584    932
1  강동구   773        379     99    155    377
2  강북구   748        369    120    138    204
3  강서구   884        388    258    184     81
4  관악구  1496        846    260    390    613

In [93]:
# 컬럼명변경 : 원본 반영안됨, 복사본에만 반영됨,
# 원본에 반영하는 방법 2가지
# 1. 다시대입 : 기관명 -> 구별
CCTV_Seoul = CCTV_Seoul.rename(columns=gu)
CCTV_Seoul.columns

# 2. inplace=True : 구별-> 기관명
gu = {
    CCTV_Seoul.columns[0] : '기관명'
}
CCTV_Seoul.rename(columns=gu, inplace=True)
CCTV_Seoul.columns

# 3. 기관명 => 구별
gu = {
    CCTV_Seoul.columns[0] : '구별'
}
CCTV_Seoul.rename(columns=gu, inplace=True)
CCTV_Seoul.columns

Index(['구별', '소계', '2013년도 이전', '2014년', '2015년', '2016년'], dtype='object')

In [94]:
# 엑셀파일 확장자 : xls, xlsx 

---
#### 인구현황 데이터 처리 
---


In [95]:
# 엑셀 파일 읽기 
# 엑셀파일 확장자 : xls(xlrd module), xlsx(openyxl module install) 
# conda install xlrd openyxl
import pandas as pd
POP_seoul = pd.read_excel(
    './data/data/01. population_in_Seoul.xls',
    header=2
)
POP_seoul

기간   자치구         세대           계         남자         여자        계.1  \
0   2017.1/4    합계  4202888.0  10197604.0  5000005.0  5197599.0  9926968.0   
1   2017.1/4   종로구    72654.0    162820.0    79675.0    83145.0   153589.0   
2   2017.1/4    중구    59481.0    133240.0    65790.0    67450.0   124312.0   
3   2017.1/4   용산구   106544.0    244203.0   119132.0   125071.0   229456.0   
4   2017.1/4   성동구   130868.0    311244.0   153768.0   157476.0   303380.0   
5   2017.1/4   광진구   158960.0    372164.0   180992.0   191172.0   357211.0   
6   2017.1/4  동대문구   159839.0    369496.0   182932.0   186564.0   354079.0   
7   2017.1/4   중랑구   177548.0    414503.0   206102.0   208401.0   409882.0   
8   2017.1/4   성북구   188512.0    461260.0   224076.0   237184.0   449773.0   
9   2017.1/4   강북구   141554.0    330192.0   161686.0   168506.0   326686.0   
10  2017.1/4   도봉구   136613.0    348646.0   171026.0   177620.0   346629.0   
11  2017.1/4   노원구   219957.0    569384.0   276823.0   292561.0   565565.0   
12  2017.1/4   은평구   201869.0    494388.0   240220.0   254168.0   489943.0   
13  2017.1/4  서대문구   137207.0    327163.0   156765.0   170398.0   314982.0   
14  2017.1/4   마포구   169404.0    389649.0   185889.0   203760.0   378566.0   
15  2017.1/4   양천구   176921.0    479978.0   237117.0   242861.0   475949.0   
16  2017.1/4   강서구   247696.0    603772.0   294433.0   309339.0   597248.0   
17  2017.1/4   구로구   172272.0    447874.0   224436.0   223438.0   416487.0   
18  2017.1/4   금천구   105146.0    255082.0   130558.0   124524.0   236353.0   
19  2017.1/4  영등포구   165462.0    402985.0   202573.0   200412.0   368072.0   
20  2017.1/4   동작구   173033.0    412520.0   201217.0   211303.0   400456.0   
21  2017.1/4   관악구   253826.0    525515.0   264763.0   260752.0   507203.0   
22  2017.1/4   서초구   173856.0    450310.0   216264.0   234046.0   445994.0   
23  2017.1/4   강남구   234107.0    570500.0   273301.0   297199.0   565550.0   
24  2017.1/4   송파구   259883.0    667483.0   325040.0   342443.0   660584.0   
25  2017.1/4   강동구   179676.0    453233.0   225427.0   227806.0   449019.0   
26       NaN   NaN        NaN         NaN        NaN        NaN        NaN   

         남자.1       여자.1       계.2      남자.2      여자.2  세대당인구   65세이상고령자  
0   4871560.0  5055408.0  270636.0  128445.0  142191.0   2.36  1321458.0  
1     75611.0    77978.0    9231.0    4064.0    5167.0   2.11    25425.0  
2     61656.0    62656.0    8928.0    4134.0    4794.0   2.09    20764.0  
3    111167.0   118289.0   14747.0    7965.0    6782.0   2.15    36231.0  
4    150076.0   153304.0    7864.0    3692.0    4172.0   2.32    39997.0  
5    174599.0   182612.0   14953.0    6393.0    8560.0   2.25    42214.0  
6    177021.0   177058.0   15417.0    5911.0    9506.0   2.22    54173.0  
7    204265.0   205617.0    4621.0    1837.0    2784.0   2.31    56774.0  
8    219545.0   230228.0   11487.0    4531.0    6956.0   2.39    64692.0  
9    160353.0   166333.0    3506.0    1333.0    2173.0   2.31    54813.0  
10   170289.0   176340.0    2017.0     737.0    1280.0   2.54    51312.0  
11   275211.0   290354.0    3819.0    1612.0    2207.0   2.57    71941.0  
12   238337.0   251606.0    4445.0    1883.0    2562.0   2.43    72334.0  
13   152613.0   162369.0   12181.0    4152.0    8029.0   2.30    48161.0  
14   181346.0   197220.0   11083.0    4543.0    6540.0   2.23    48765.0  
15   235278.0   240671.0    4029.0    1839.0    2190.0   2.69    52975.0  
16   291249.0   305999.0    6524.0    3184.0    3340.0   2.41    72548.0  
17   207114.0   209373.0   31387.0   17322.0   14065.0   2.42    56833.0  
18   120334.0   116019.0   18729.0   10224.0    8505.0   2.25    32970.0  
19   183705.0   184367.0   34913.0   18868.0   16045.0   2.22    52413.0  
20   195775.0   204681.0   12064.0    5442.0    6622.0   2.31    56013.0  
21   256090.0   251113.0   18312.0    8673.0    9639.0   2.00    68082.0  
22   214036.0   231958.0    4316.0    2228.0    2088.0   2.57    51733.0  
23   270726.0   294824.0 

In [96]:
# series에 index 지정 방식이 두가지 있음
# 1. 정수 인덱스 : integer index
# 2. 문자열 인덱스 : named index


In [97]:
# series 생성 1 방식식
data = [10,20,30,40,50] # list
index = ['a','b','c','d','e'] # 날짜 시간이 들어갈 수 있다다
series = pd.Series(data=data, index=index)
print(series)
print(series['a'])

a    10
b    20
c    30
d    40
e    50
dtype: int64
10


In [98]:
# series 2번째 방식 만들기
data_index = {
    'a' : 10
    , 'b' : 20
    , 'c' : 30
    , 'd' : 40
    , 'e' : 50
}

series = pd.Series(data_index)
print(series)

a    10
b    20
c    30
d    40
e    50
dtype: int64


In [99]:
# series 3번째 방식
# 스칼라값(단일값)과 인덱스 리스트로 시리즈 생성 
data = 5 #스칼라값
index = ['a','b','c']
series = pd.Series(data=data, index=index)
series

a    5
b    5
c    5
dtype: int64

In [100]:
# 4번쨰 series 방식
series = pd.Series(
    data=[1,2,3]
    , index=['a','b','c']
    , name='sample_series'
    , dtype='int8'
)
series

a    1
b    2
c    3
Name: sample_series, dtype: int8

In [101]:
# PDF in[10] : nan(not a number) : 결측치, 무한대 의미가 있다
import numpy as np

s = pd.Series([1,3,5,np.nan,6,8]) # data argument가 첫번째다
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [102]:
# 판다스에서 날짜 시간 데이터 생성 : data_range()->범위
import pandas as pd

dates = pd.date_range(
    '20250227' #시작일
    , periods=6
    , freq='ME' # freq='D' 는 날짜
)
datesS

NameError: name 'datesS' is not defined

In [ ]:
print(np.arange(24))
print(np.arange(24).shape)
print(np.arange(24).reshape(6,4))
print(np.random.randn(6,4))
np.arange(24) # array range


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
(24,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[-1.0684212  -0.41233886  0.70782354  1.39150814]
 [ 1.7399143   1.0813649  -2.0531469   0.56464205]
 [-1.70954784 -0.64071095  1.17340719 -0.02351321]
 [ 0.74189954 -1.53881937  0.42599762 -1.51585344]
 [-0.39013865 -0.76008531  1.11029277 -0.08857653]
 [-0.68968377  1.72269399  0.93730338  1.18137213]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
# DF 생성
import numpy as np
df = pd.DataFrame(
    np.arange(24).reshape(6,4) #data
    , index=dates
    , columns=['A','B','C','D']
)
df

A   B   C   D
2025-02-28   0   1   2   3
2025-03-31   4   5   6   7
2025-04-30   8   9  10  11
2025-05-31  12  13  14  15
2025-06-30  16  17  18  19
2025-07-31  20  21  22  23

In [ ]:
print(df.index)
print(df.columns)
print(df.values)

DatetimeIndex(['2025-02-28', '2025-03-31', '2025-04-30', '2025-05-31',
               '2025-06-30', '2025-07-31'],
              dtype='datetime64[ns]', freq='ME')
Index(['A', 'B', 'C', 'D'], dtype='object')
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [ ]:
# 데이터 구조, 정보 확인
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 6 entries, 2025-02-28 to 2025-07-31
Freq: ME
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       6 non-null      int64
 1   B       6 non-null      int64
 2   C       6 non-null      int64
 3   D       6 non-null      int64
dtypes: int64(4)
memory usage: 240.0 bytes


In [ ]:
# 기본통계
df.describe()

A          B          C          D
count   6.000000   6.000000   6.000000   6.000000
mean   10.000000  11.000000  12.000000  13.000000
std     7.483315   7.483315   7.483315   7.483315
min     0.000000   1.000000   2.000000   3.000000
25%     5.000000   6.000000   7.000000   8.000000
50%    10.000000  11.000000  12.000000  13.000000
75%    15.000000  16.000000  17.000000  18.000000
max    20.000000  21.000000  22.000000  23.000000

In [ ]:
# 데이터 처리
# 1.정렬(오름차순(ascending), 내림차순)
# B컬럼의 값으로 내림차순
# df.sort_values(by='컬럼명', ascending=True, False)
df.sort_values(by='B', ascending=False) #원본에 반영되지 않았다다


A   B   C   D
2025-07-31  20  21  22  23
2025-06-30  16  17  18  19
2025-05-31  12  13  14  15
2025-04-30   8   9  10  11
2025-03-31   4   5   6   7
2025-02-28   0   1   2   3

In [ ]:
df

A   B   C   D
2025-02-28   0   1   2   3
2025-03-31   4   5   6   7
2025-04-30   8   9  10  11
2025-05-31  12  13  14  15
2025-06-30  16  17  18  19
2025-07-31  20  21  22  23

In [ ]:
# 시리즈에 인덱싱,  슬라이싱 : PDF in[22]
# df dataframe 에서 시리즈 추출 : 컬럼 한개는 시리즈다다
df['A']


2025-02-28     0
2025-03-31     4
2025-04-30     8
2025-05-31    12
2025-06-30    16
2025-07-31    20
Freq: ME, Name: A, dtype: int64

In [ ]:
# # in[23] : 데이터 ㅍ레임에서 슬라이싱
# df[0:3]

# A	B	C	D
# 2025-02-28	0	1	2	3
# 2025-03-31	4	5	6	7
# 2025-04-30	8	9	10	1
df['20250228':'20250430']
# named index 에서 주의 : 1.end-1 안된다
# 슬라이싱 : return DataFrame


A  B   C   D
2025-02-28  0  1   2   3
2025-03-31  4  5   6   7
2025-04-30  8  9  10  11

In [ ]:
# in[25]
# df.loc['20250228'] named index => 행단위 추출
df.iloc[0] # integer index -> 행단위 추출


A    0
B    1
C    2
D    3
Name: 2025-02-28 00:00:00, dtype: int64

In [ ]:
# loc, iloc 데이터 추출 : loc[], iloc[]
# 1. loc[행,열]
# df.loc[start : end, ['A','C']], [['A','C']] : A, C 컬럼만 추출 => 팬시색인
df.loc[ : , ['A','C']]

A   C
2025-02-28   0   2
2025-03-31   4   6
2025-04-30   8  10
2025-05-31  12  14
2025-06-30  16  18
2025-07-31  20  22

In [ ]:
# 날짜 인덱스로 접근
df.loc['20250227':'20250430']

A  B   C   D
2025-02-28  0  1   2   3
2025-03-31  4  5   6   7
2025-04-30  8  9  10  11

In [ ]:
df.loc['20250227':'20250430',['A','D']] # : => 슬라이싱 : ,여러개 추출

A   D
2025-02-28  0   3
2025-03-31  4   7
2025-04-30  8  11

In [ ]:
# dataframe 에서 인덱싱(슬라이싱)
# 인덱싱, 슬라이싱, 펜시섹인, 블린인덱싱
# 블린(조건) 인덱싱 : 조건에 맞는 데이터만 추출
print(df)
# print (df[df['A'] < 5])
df['A'] < 5


             A   B   C   D
2025-02-28   0   1   2   3
2025-03-31   4   5   6   7
2025-04-30   8   9  10  11
2025-05-31  12  13  14  15
2025-06-30  16  17  18  19
2025-07-31  20  21  22  23


2025-02-28     True
2025-03-31     True
2025-04-30    False
2025-05-31    False
2025-06-30    False
2025-07-31    False
Freq: ME, Name: A, dtype: bool

In [ ]:
# df2 = df 복사가 아니다
df2 = df.copy()
id(df2) is id(df)

False

In [ ]:
# in[38] : 데이터프레임에서 컬럼 추가
df2['E'] = ['one','one','two','three','four','three']
df2

A   B   C   D      E
2025-02-28   0   1   2   3    one
2025-03-31   4   5   6   7    one
2025-04-30   8   9  10  11    two
2025-05-31  12  13  14  15  three
2025-06-30  16  17  18  19   four
2025-07-31  20  21  22  23  three

In [ ]:
# IN[39] : isin([여러개]) method : 블린인덱싱
# df2['E'] series object
df2['E'].isin(['two'])
# in[40]
df[df2['E'].isin(['two','four'])]
# df[조건식] : true 행 추출 


A   B   C   D
2025-04-30   8   9  10  11
2025-06-30  16  17  18  19

---
#### date_range function
---
- 용도 : 일정 기간 동안의 날짜 범위를 생성하는데 사용, 주로 시계열 데이터 처리에 유용
- date_range(start, end, periods, freq, tz.....)

In [ ]:
dates = pd.date_range('20250227', periods=7)
print(dates)

DatetimeIndex(['2025-02-27', '2025-02-28', '2025-03-01', '2025-03-02',
               '2025-03-03', '2025-03-04', '2025-03-05'],
              dtype='datetime64[ns]', freq='D')


In [ ]:
series = pd.Series(
    data=[1,2,3,4,5,6,7]
    , index= dates
)
print(series)
# 슬라이싱 : 연속된 데이터 추출 
print(series['20250228':'20250302'])

2025-02-27    1
2025-02-28    2
2025-03-01    3
2025-03-02    4
2025-03-03    5
2025-03-04    6
2025-03-05    7
Freq: D, dtype: int64
2025-02-28    2
2025-03-01    3
2025-03-02    4
Freq: D, dtype: int64


In [ ]:
# 범위의 날짜로 생성 : 일단위 생성 
data_range = pd.date_range(
    start='20250228'
    , end='20250618'
)
print(data_range)

DatetimeIndex(['2025-02-28', '2025-03-01', '2025-03-02', '2025-03-03',
               '2025-03-04', '2025-03-05', '2025-03-06', '2025-03-07',
               '2025-03-08', '2025-03-09',
               ...
               '2025-06-09', '2025-06-10', '2025-06-11', '2025-06-12',
               '2025-06-13', '2025-06-14', '2025-06-15', '2025-06-16',
               '2025-06-17', '2025-06-18'],
              dtype='datetime64[ns]', length=111, freq='D')


In [ ]:
# freq : 생성할 날짜 시간의 단위 지정 
# 시간 단위생성 
date_range = pd.date_range(
    start='20250228'
    , periods=10
    , freq='H'
)
print(date_range)

DatetimeIndex(['2025-02-28 00:00:00', '2025-02-28 01:00:00',
               '2025-02-28 02:00:00', '2025-02-28 03:00:00',
               '2025-02-28 04:00:00', '2025-02-28 05:00:00',
               '2025-02-28 06:00:00', '2025-02-28 07:00:00',
               '2025-02-28 08:00:00', '2025-02-28 09:00:00'],
              dtype='datetime64[ns]', freq='h')


C:\Users\jh\AppData\Local\Temp\ipykernel_25816\3494491799.py:3: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  date_range = pd.date_range(


In [ ]:
# freq=value
# value
# D = 일단위, B: 주말을 제외한 평일, N: 시간단위, T:분단위, S:초단위, L:밀리초
# w : 주단위, M: 월단위, Q: 분기 단위, Y : 연단위

In [ ]:
# 영업일(B) 
date_range = pd.date_range(
    start='20250228'
    , periods=10  
    , freq='T' #'min' # 'w'
)
print(date_range)

DatetimeIndex(['2025-02-28 00:00:00', '2025-02-28 00:01:00',
               '2025-02-28 00:02:00', '2025-02-28 00:03:00',
               '2025-02-28 00:04:00', '2025-02-28 00:05:00',
               '2025-02-28 00:06:00', '2025-02-28 00:07:00',
               '2025-02-28 00:08:00', '2025-02-28 00:09:00'],
              dtype='datetime64[ns]', freq='min')


C:\Users\jh\AppData\Local\Temp\ipykernel_25816\2559241550.py:2: FutureWarning: 'T' is deprecated and will be removed in a future version, please use 'min' instead.
  date_range = pd.date_range(


In [ ]:
# 날짜 인덱스 생성 
import numpy as np
import pandas as np
from datetime import datetime

now = datetime.now()
print(now)

date_idx = pd.date_range(
    start=now
    , periods=6
)
print(date_idx)

2025-03-06 13:35:12.330268
DatetimeIndex(['2025-03-06 13:35:12.330268', '2025-03-07 13:35:12.330268',
               '2025-03-08 13:35:12.330268', '2025-03-09 13:35:12.330268',
               '2025-03-10 13:35:12.330268', '2025-03-11 13:35:12.330268'],
              dtype='datetime64[ns]', freq='D')


---
#### 인덱싱, 슬라이싱(인덱싱), 펜시섹인(인덱싱), 블린인덱싱 
---

- 행이나 컬럼 추출 목적 
- 1. 행 기준 추출 : loc[], iloc[]
- 2. 컬럼 기준 추출 : ['컬럼명'], [['컬럼명','컬럼명']]
- 3. 인덱싱 : 정수 인덱스 사용 , 네임드 인덱스 사용


In [ ]:
# 인덱싱, 슬라이싱 
# 정수인덱스, 네임드인덱스
data = {
      'Name' : ['홍길동','고길동','마이꼴','둘리','희동']
    , 'Age' : [20,30,20,1000,2]
    , 'Addr' : ['울릉도','서울','서울','별','서울']
}
df = pd.DataFrame(data)
df

Name   Age Addr
0  홍길동    20  울릉도
1  고길동    30   서울
2  마이꼴    20   서울
3   둘리  1000    별
4   희동     2   서울

In [ ]:
print(df['Name'])
print(df['Age'])
print(df['Addr'])
# 인덱스는 '키'다 

0    홍길동
1    고길동
2    마이꼴
3     둘리
4     희동
Name: Name, dtype: object
0      20
1      30
2      20
3    1000
4       2
Name: Age, dtype: int64
0    울릉도
1     서울
2     서울
3      별
4     서울
Name: Addr, dtype: object


In [ ]:
print(df.loc[0.:])
print(df.iloc[0.:])
print(df)

  Name   Age Addr
0  홍길동    20  울릉도
1  고길동    30   서울
2  마이꼴    20   서울
3   둘리  1000    별
4   희동     2   서울


TypeError: cannot do positional indexing on RangeIndex with these indexers [0.0] of type float

In [ ]:
df

Name   Age Addr
0  홍길동    20  울릉도
1  고길동    30   서울
2  마이꼴    20   서울
3   둘리  1000    별
4   희동     2   서울

In [ ]:
# 특정 컬럼을 인덱스로 보내는 작업 
# set_index(지정한 컬럼)
df = df.set_index('Name')

In [ ]:
# 홍길동의 데이터 추출(행추출) :
df.loc['홍길동']

Age      20
Addr    울릉도
Name: 홍길동, dtype: object

In [ ]:
# 펜시섹인 : 홍길동 마이콜 추출
df.loc[['홍길동','마이꼴']]

Age Addr
Name          
홍길동    20  울릉도
마이꼴    20   서울

In [ ]:
# 블린 인덱싱 
# 나이가 20 이상인 데이터 추출 
df['Age'] > 20

Name
홍길동    False
고길동     True
마이꼴    False
둘리      True
희동     False
Name: Age, dtype: bool

In [ ]:
df[df['Age']>20]

Age Addr
Name           
고길동     30   서울
둘리    1000    별

In [ ]:
# 슬라이싱 : 고길동부터 둘리 행단위 추출 
df.loc['고길동':'둘리']

Age Addr
Name           
고길동     30   서울
마이꼴     20   서울
둘리    1000    별

In [ ]:
# 구분 컬럼 추가 
df['gubun'] = ['가족','친구','회사','기타','가족']
df

Age Addr gubun
Name                 
홍길동     20  울릉도    가족
고길동     30   서울    친구
마이꼴     20   서울    회사
둘리    1000    별    기타
희동       2   서울    가족

In [ ]:
# 가족, 친구 검색 
# 블린 인덱스 
df['gubun'].isin(['가족','친구']) #boolean return

Name
홍길동     True
고길동     True
마이꼴    False
둘리     False
희동      True
Name: gubun, dtype: bool

In [ ]:
df[df['gubun'].isin(['가족','친구'])]

Age Addr gubun
Name                
홍길동    20  울릉도    가족
고길동    30   서울    친구
희동      2   서울    가족

In [ ]:
print(df.loc['20250430','C']) # 
print(df.iloc[2,3]) # integer index


10
11


In [ ]:
# C clumn 
df.loc['20250301']
print(df['C'])
print(df.loc[:,'C'])
print(df)


KeyError: '20250301'

In [ ]:
# in[31] integer index 사용한 슬라이싱 
# end -1
df.iloc[3:5,0:2]



A   B
2025-05-31  12  13
2025-06-30  16  17

In [ ]:
# csv 파일읽기
# 3. cctv 현황
import pandas as pd
import numpy as np
CCTV_Seoul = pd.read_csv(
    './data/data/01. CCTV_result.csv' # cctv 현황 중간 데이터.csv
    , encoding='utf-8'
    , index_col=0 #0번 컬럼을 인덱스로 보내라
)
CCTV_Seoul.head()

소계       최근증가율       인구수       한국인      외국인      고령자     외국인비율  \
구별                                                                      
강남구  2780  150.619195  570500.0  565550.0   4950.0  63167.0  0.867660   
강동구   773  166.490765  453233.0  449019.0   4214.0  54622.0  0.929765   
강북구   748  125.203252  330192.0  326686.0   3506.0  54813.0  1.061806   
강서구   884  134.793814  603772.0  597248.0   6524.0  72548.0  1.080540   
관악구  1496  149.290780  525515.0  507203.0  18312.0  68082.0  3.484582   

         고령자비율    CCTV비율           오차  
구별                                     
강남구  11.072217  0.487292  1388.055355  
강동구  12.051638  0.170552   465.422892  
강북구  16.600342  0.226535   329.342026  
강서구  12.015794  0.146413   551.503155  
관악구  12.955291  0.284673   162.948104

In [ ]:
# 인구현황 데이터 일기
POP_seoul = pd.read_csv(
    './data/data/01 인구현황 nan 삭제까지.csv' # dl 인구현황 nan 삭제까지.csv
    , encoding='utf-8'
    , 
)
POP_seoul.head()

Unnamed: 0   구별       인구수       한국인      외국인      고령자
0           1  종로구  162820.0  153589.0   9231.0  25425.0
1           2   중구  133240.0  124312.0   8928.0  20764.0
2           3  용산구  244203.0  229456.0  14747.0  36231.0
3           4  성동구  311244.0  303380.0   7864.0  39997.0
4           5  광진구  372164.0  357211.0  14953.0  42214.0

In [ ]:
# 인구현환에서 외국인, 고령자 비율 구하기 (인구수 대비)
# 새로운 컬럼 생성해서 대입
POP_seoul['외국인비율'] = POP_seoul['외국인'] / POP_seoul['인구수'] * 100
POP_seoul['고령자비율'] = POP_seoul['고령자'] / POP_seoul['인구수'] * 100

POP_seoul.head()



Unnamed: 0   구별       인구수       한국인      외국인      고령자     외국인비율      고령자비율
0           1  종로구  162820.0  153589.0   9231.0  25425.0  5.669451  15.615404
1           2   중구  133240.0  124312.0   8928.0  20764.0  6.700690  15.583909
2           3  용산구  244203.0  229456.0  14747.0  36231.0  6.038828  14.836427
3           4  성동구  311244.0  303380.0   7864.0  39997.0  2.526635  12.850689
4           5  광진구  372164.0  357211.0  14953.0  42214.0  4.017852  11.342849

In [ ]:
# 인구수 정렬
# pop_seoul : dataframe object 
POP_seoul.sort_values(
    by='외국인비율'
    , ascending=False    
).head()


Unnamed: 0    구별       인구수       한국인      외국인      고령자     외국인비율  \
18          19  영등포구  402985.0  368072.0  34913.0  52413.0  8.663598   
17          18   금천구  255082.0  236353.0  18729.0  32970.0  7.342345   
16          17   구로구  447874.0  416487.0  31387.0  56833.0  7.007998   
1            2    중구  133240.0  124312.0   8928.0  20764.0  6.700690   
2            3   용산구  244203.0  229456.0  14747.0  36231.0  6.038828   

        고령자비율  
18  13.006191  
17  12.925255  
16  12.689506  
1   15.583909  
2   14.836427

In [ ]:
# 고령자 데이터 확인
POP_seoul.sort_values(
    by='고령자'
    , ascending=False
).head()

Unnamed: 0   구별       인구수       한국인      외국인      고령자     외국인비율      고령자비율
15          16  강서구  603772.0  597248.0   6524.0  72548.0  1.080540  12.015794
23          24  송파구  667483.0  660584.0   6899.0  72506.0  1.033584  10.862599
11          12  은평구  494388.0  489943.0   4445.0  72334.0  0.899091  14.631019
10          11  노원구  569384.0  565565.0   3819.0  71941.0  0.670725  12.634883
20          21  관악구  525515.0  507203.0  18312.0  68082.0  3.484582  12.955291

In [ ]:
# cctv 인구현황 dataframe 병합


#### dataFrame

In [ ]:
# 인덱싱 , 슬라이싱 , 펜시 섹인, 블린 인덱싱 
# 
print(df)


In [ ]:
# 3개 데이터프레임을 병합 : concat(데이터 프레임틀)
result = pd.concat(
       
)

In [ ]:
result = pd.concat(
    [df1, df2, df3]
    , axls=0
    , keys=['df1','df2','df3'] #임의대로 바꿀 수 있음
)
result


NameError: name 'df1' is not defined

In [ ]:
#이 결과에서 index 다루기 
result.index

NameError: name 'result' is not defined

In [ ]:
result.index.get_level_values(0)

NameError: name 'result' is not defined

In [ ]:
result.index.get_level_values(0)

NameError: name 'result' is not defined

In [ ]:
result.index.get_level_values(1)

NameError: name 'result' is not defined

In [ ]:
result

In [ ]:
# 새로운 데이터 프레임 생성 : df4 => 컬럼은 'B','D' 'F'
# df4, df1 병합
df4 = 

In [ ]:
# df1, df4 변합 
df1, df4 


In [ ]:
result = pd.concat(
    [df1, df4]
    , axls=1
    , join='outer' # 디폴트 , 풀아우터 조인
)

In [ ]:
# 이너조인 : 키가 동일한 것만 조인
result = pd.concat(
    [df1, df4]
    , axls=1
    , join='inner'
)
result

In [ ]:
# 아래로 병합 : axis=0
result = pd.concat(
    [df1, df4]
    ,axis=0
    , join='inner'
)
result

In [ ]:
result = pd.concat(
    [df1, df4]
    , axis=1
    , join='outer'
    , join_axes=[df1.index] #error
)
result

In [ ]:
# axis=0, join=
result = pd.concat(
    [df1,df4]
    , ignore_index==true 
)
result

In [ ]:
# merge 로 변합
# mnerge ()
left, right



In [ ]:
pd.merge( # 특정 컬럼의 값으로 조인할 댸 사용 # concat , merge 중요요
    left=left
    , right=right
    , on='key' #조인할 컬럼명 지정
    , how='outer' # inner join default
    , how='inner' # inner join default
    , how='left' # inner join default
    , how='right' # inner join default
)

SyntaxError: keyword argument repeated: how (2259818826.py, line 6)

In [ ]:
#### cctv, 인구현황 병합 분석석

In [ ]:
# 데이터 확인
CCTV_Seoul.head()

구별    소계       최근증가율       인구수       한국인      외국인      고령자     외국인비율  \
0  강남구  2780  150.619195  570500.0  565550.0   4950.0  63167.0  0.867660   
1  강동구   773  166.490765  453233.0  449019.0   4214.0  54622.0  0.929765   
2  강북구   748  125.203252  330192.0  326686.0   3506.0  54813.0  1.061806   
3  강서구   884  134.793814  603772.0  597248.0   6524.0  72548.0  1.080540   
4  관악구  1496  149.290780  525515.0  507203.0  18312.0  68082.0  3.484582   

       고령자비율    CCTV비율           오차  
0  11.072217  0.487292  1388.055355  
1  12.051638  0.170552   465.422892  
2  16.600342  0.226535   329.342026  
3  12.015794  0.146413   551.503155  
4  12.955291  0.284673   162.948104

In [ ]:
# 인구현황 데이터 확인 # merge : 값으로 
POP_seoul.head()

기간  자치구         세대           계         남자         여자        계.1  \
0  2017.1/4   합계  4202888.0  10197604.0  5000005.0  5197599.0  9926968.0   
1  2017.1/4  종로구    72654.0    162820.0    79675.0    83145.0   153589.0   
2  2017.1/4   중구    59481.0    133240.0    65790.0    67450.0   124312.0   
3  2017.1/4  용산구   106544.0    244203.0   119132.0   125071.0   229456.0   
4  2017.1/4  성동구   130868.0    311244.0   153768.0   157476.0   303380.0   

        남자.1       여자.1       계.2      남자.2      여자.2  세대당인구   65세이상고령자  
0  4871560.0  5055408.0  270636.0  128445.0  142191.0   2.36  1321458.0  
1    75611.0    77978.0    9231.0    4064.0    5167.0   2.11    25425.0  
2    61656.0    62656.0    8928.0    4134.0    4794.0   2.09    20764.0  
3   111167.0   118289.0   14747.0    7965.0    6782.0   2.15    36231.0  
4   150076.0   153304.0    7864.0    3692.0    4172.0   2.32    39997.0

In [ ]:
# cctv, 인구현황 merge 
data_result = pd.merge(
    left=CCTV_Seoul#left
    , right=POP_seoul# right
    , on='구별'  # 조인조건, 조인할 컬럼 지정 
    , how='inner'  # 조인 방법 (inner, outer, left outer, right outer)
)
data_result.head()

NameError: name 'pd' is not defined

In [ ]:
# 불팔요한 컬럼 삭제 , dataframe => drop메소드 사용 필요 
del data_result['2013년도 이전'] #series object 삭제
del data_result['2014년'] #series object 삭제
del data_result['2015년'] #series object 삭제
del data_result['2016년'] #series object 삭제

data_result.head()


NameError: name 'data_result' is not defined

In [ ]:
# 구별이라는 컬럼을 키로 사용하기 위해 => 인덱스로 보내는게 상당히 데이터처리, 차트 처리시 편리하다
# data_result.set_index(컬럼명, inplace=true)
data_result.set_index('구별', inplace=True)
data_result.head()
# 소계 : 전체 cctv 개수수

In [ ]:
print( df[df['A'<S]
         

In [ ]:
# 소계와 인구현황 컬럼들과 상관계수를 출력
# 상관계수 :  -1 ~ 1 , 0에 가까우면 관게 없다,
# 넘파이에 상관 계수를 구하는 함수 : corrcoef(컬럼들)
# 인구수와 소계(cctv개수)
np.corrcoef(data_result['인구수'], data_result['소계'])
#  0.15 가 넘어가면 상관관계를 넘어간다, 


In [ ]:
---
#### 데이터 시각화 
---

plot 종류 
1. 라인 플롯
2. 스캐터 플롯 
3. 바 차트
4. 히스토그램
5. 박스플롯 
6. 컨투어 플롯


In [ ]:
# 경고를 무시해라 -> 화면에 표시하지 마라.
import warnings
warnings.filterwarnings('ignore')
#
# 시각화 단계
# 1. 도화지 준비 (그릴 준비하는 것) : figjre()
plt.figure(
    figsize=(3,3)
)
plt.plot([1,2,3,4,5,6])

plt.show

NameError: name 'plt' is not defined

In [ ]:
# 
plt.figure(figure(4,4))
plt.title('시각화 연습') # 한글 꺠지는 거 방지지

plt.plot([10,20,30,40],[1,4,9,16])
plt.show()


NameError: name 'plt' is not defined

In [ ]:
# line plot 
# range() -> return list
# arange() -> return ndarray (numpy)
t = np.arange(0,12,0.01) # (시작값, 종료값, 스텝)
len(t)

NameError: name 'np' is not defined

In [ ]:
# 선그래프 
plt.figure(figsize=[6,4])
plt.plot(s,y)
plt.show()
plt.title('Example of sinewave')
plt.grid() # 구라드 표시해 줄 떄 사용 
plt.xlabel('time')
pit.ylabel('Amplitudde')
pit.xlim(0,np,p1)
# cos =0 dlf eo, 1, 

In [ ]:
# 선그래프 
plt.figure(figsize=[6,4])
plt.plot(s,y)
plt.show()
plt.title('Example of sinewave')
plt.grid() # 구라드 표시해 줄 떄 사용 
plt.xlabel('time')
pit.ylabel('Amplitudde')
pit.xlim(0,np,p1)
# cos =0 dlf eo, 1, 

In [ ]:
# 선의 모양, 두께, 색 지정
#  데이터 생성
t = np.arange(0,5,0.5) # t : red => deshed(모양)
plt.plot(t,t**2, 'bs') # 마커모양 (사각형)
plt.plot(t,t**3, 'bs') # 마커모양 (사각형)
plt.show()


NameError: name 'np' is not defined

In [ ]:
# 실그래프 설정
# 데이터 
x = [0,1,2,3,4,5,6]
y = []

plt.plot(
    x, t, color='red'
    , linewidth=2
    , linestyle='dotted'
    , marker='0' # 점모양
    , merkeredgecolor='b' # 점의 경계선 색 blue
    , markerfacecolor='k' # 점의 면색을 지정, black:k
    , merkeredgewidth=3 # 점의 경계선 두께 지정
    , markersize=12 #점의 크기 
)
plt.show()

NameError: name 'plt' is not defined

In [ ]:
# 산정도 : scatter(점찍기) -> 데이터 분포 확인시 사용 , 데이터의 상관 관계를 확인할 때 사용 
x1 = np.arange(0,10) 
x2 = np.array([9,8,7,9,8,3,2,4,3,4])


NameError: name 'np' is not defined

In [ ]:
colomap = s1
plt.figure(figure=(5,3))
plt.scatter(x1,x2, marker='>', s=50, c=colomap)
plt.colorbar()
plt.show()


---
#### cctv와 인구현황 그래프로 분석 
---

In [ ]:
data_result.head()

NameError: name 'data_result' is not defined

In [ ]:
import matplotlib as cm
# 데이터 프레임에서 차트를 구성 할 수 있다
data_result['소계'].plot(
    kind='bar'
    , grid=True
    , figsize=(4,5)
    , colormap='blue'
)

In [ ]:
# 데이터 가공 시각화 : 소계 / 인구수 * 100
data_result['cctv비율'] = data_result

In [ ]:
# 인구수에 비해 cctv 대수가 많은 곳을 분석, 시각화
data_result['cctv비율'].sort_values().plot
  kind='barh'
    , grid=True
    , figsize=5
    

In [ ]:
# scatter 
# 
plt.figure()

plt.scatter(
    data_result['인구수']
    , data_result['소계']
    , s=50
)
plt.plot(
    fx # x축 ㅣ 10~70만 인구수 100개 
    , f1(fx)
    , ls='dashed'
    , color='g'
)
plt.title('인구 대비 CCTV 개수')
plt.xlabel('인구수')
plt.ylabel('CCTV 개수')
plt.grid()
plt.colorbar()
plt.show()

plt.scatter(data_result['인구 수']), data_result
, c=data_result['오차']


In [ ]:
# 직선의 함수 구하기 
# 개수 찾기 f(x) = a*x + b 에서 a,b 찾기 : np.polyfit()
fp1 = np.polyfit(data_result['인구수'], data_result['소계'],1)
print(fp1)
#  2. 위 계수로 1차 함수 오브젝트 생성 : np.ployid(p) (결과)
f1 = np.poly1d(fp1)
f1

NameError: name 'data_result' is not defined

In [ ]:
# np.linspace(구간시작, 구간끝, 구간나누어져 나온 개수)

for pop in np.linspace(100000,700000, 7):
    print(pop, ' : ',f1(pop))
f1(100000), f1(700000)

NameError: name 'f1' is not defined

In [ ]:
fx = np.linspace(10000, 70000, 200) #100개 


In [ ]:
# 오차구하기 : 너무 많거나 적거나 한 '구'를 찾기 10개
data_result['오차'] = \
    np.abs(data_result['소계'] - f1(data_result['인구수']))

data_result.sort_values(by='오차', ascending=False)['오차'].head(10)

NameError: name 'data_result' is not defined

In [ ]:
# 오차로 정렬한 데이터 프레임 생성 
df_sort = data_result.sort_values(by='오차')


In [ ]:
print(data_result.index)
print(len(data_result.index))
for n in range(len(data_result.index))

NameError: name 'data_result' is not defined

In [103]:
# scatter 
# 
plt.figure()

plt.scatter(
    data_result['인구수']
    , data_result['소계']
    , s=50
)
plt.plot(
    fx # x축 ㅣ 10~70만 인구수 100개 
    , f1(fx)
    , ls='dashed'
    , color='g'
)

for n in range(len(df_sort.index)):
    plt.text(
      df_sort('')   
    )
plt.title('인구 대비 CCTV 개수')
plt.xlabel('인구수')
plt.ylabel('CCTV 개수')
plt.grid()
plt.colorbar()
plt.show()

plt.scatter(data_result['인구 수']), data_result
, c=data_result['오차']


NameError: name 'plt' is not defined

---
#### 3월 7일 범죄 현황 시각화
---
