In [1]:
# torch.to() : 텐서를 다른 장치나 데이터 타입으로 이동
import torch

tensor_=torch.tensor([1,2,3]) # int64
print(tensor_) # dram(주기억장치)
tensor_gpu = tensor_.to('cuda') # gpu vram로 이동
print(tensor_gpu)

# 데이터 타입 변경
tensor_float=tensor_.to(torch.float32)
print(tensor_float)


tensor([1, 2, 3])
tensor([1, 2, 3], device='cuda:0')
tensor([1., 2., 3.])


In [2]:
# 텐서 크기와 차원 추가, 삭제
# 전치 : transpose()
t=torch.rand(3,5)
print(t)
# t_tr=torch.transpose(t,0,1) # 
t_tr=t.transpose(0,1)
print(t.shape ,'->', t_tr.shape)

tensor([[0.0417, 0.9935, 0.8224, 0.5501, 0.4449],
        [0.0739, 0.6647, 0.2590, 0.3239, 0.5152],
        [0.5315, 0.8585, 0.6984, 0.7501, 0.8470]])
torch.Size([3, 5]) -> torch.Size([5, 3])


In [3]:
# 텐서 크기 변경 : reshape
t=torch.zeros(30) # 1차원 : 1D
print(t)
# 2D 변경 : 5,6
t_reshape=t.reshape(5,6)
print(t_reshape.shape)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.])
torch.Size([5, 6])


In [4]:
# 불필요한 차원 삭제 : squeeze
t=torch.zeros(1,2,1,4,1) # 5차원
print(t.shape)
t_sqz=t.squeeze(2)
print(t_sqz.shape)

torch.Size([1, 2, 1, 4, 1])
torch.Size([1, 2, 4, 1])


In [5]:
# 차원 추가 : unsqueeze()
import numpy as np
t=torch.tensor([1,2,3])
print(t.shape)
print(t)

# 차원 추가
u_t=t.unsqueeze(0) # 0번째 차원 추가
print(u_t.shape) # 2 차원된다
print(u_t)

# numpy
t_n=np.array([1,2,3])
print(t_n.shape)

torch.Size([3])
tensor([1, 2, 3])
torch.Size([1, 3])
tensor([[1, 2, 3]])
(3,)


In [6]:
# elment-wise:원소별 연산
# 원소별 곱셈
torch.manual_seed(1)
t1=2*torch.rand(5,2)-1
print(t1)
t2=torch.normal(mean=0, std=1, size=(5,2))
print(t2)
t3=torch.multiply(t1,t2)
print(t3)

tensor([[ 0.5153, -0.4414],
        [-0.1939,  0.4694],
        [-0.9414,  0.5997],
        [-0.2057,  0.5087],
        [ 0.1390, -0.1224]])
tensor([[ 0.8590,  0.7056],
        [-0.3406, -1.2720],
        [-1.1948,  0.0250],
        [-0.7627,  1.3969],
        [-0.3245,  0.2879]])
tensor([[ 0.4426, -0.3114],
        [ 0.0660, -0.5970],
        [ 1.1249,  0.0150],
        [ 0.1569,  0.7107],
        [-0.0451, -0.0352]])


In [7]:
print(t1)
print(torch.mean(t1,axis=1))

tensor([[ 0.5153, -0.4414],
        [-0.1939,  0.4694],
        [-0.9414,  0.5997],
        [-0.2057,  0.5087],
        [ 0.1390, -0.1224]])
tensor([ 0.0369,  0.1378, -0.1709,  0.1515,  0.0083])


In [8]:
# 행렬 곱 : dot product (내적)
tt=torch.tensor([1,2,3,4,5]).to(torch.float32)

t5 = torch.matmul(tt, t1)

print(t5)

tensor([-2.8246,  3.7193])


In [ ]:
# 텐서의 노름 연산 : 텐서의 크기(길이) 계산
print(t1)
norm_t1=torch.linalg.norm(t1, ord=2, dim=1) # ord=2 유클리드 노름 
print(norm_t1)

tensor([[ 0.5153, -0.4414],
        [-0.1939,  0.4694],
        [-0.9414,  0.5997],
        [-0.2057,  0.5087],
        [ 0.1390, -0.1224]])
tensor([0.6785, 0.5078, 1.1162, 0.5488, 0.1853])


In [19]:
# 텐서를 나누고, 쌓거나, 연결하는 함수
# chunk() : 텐서 특정 개수로 나누기
torch.manual_seed(1)

# 난수 생성 6개
t=torch.rand(6)
print(t)
# 3개로 나누기
t_c=torch.chunk(t, 3)
print(t_c)


tensor([0.7576, 0.2793, 0.4031, 0.7347, 0.0293, 0.7999])
(tensor([0.7576, 0.2793]), tensor([0.4031, 0.7347]), tensor([0.0293, 0.7999]))


In [23]:
# split() : 텐서 특정 크기로 나누기, reshape 비슷
torch.manual_seed(1)
t=torch.rand(5)
print(t)
t_s=torch.split(t, split_size_or_sections=[3,2])
print(t_s)

tensor([0.7576, 0.2793, 0.4031, 0.7347, 0.0293])
(tensor([0.7576, 0.2793, 0.4031]), tensor([0.7347, 0.0293]))


In [25]:
# 
tensor_=torch.arange(10)
print(tensor_)
splits=torch.split(tensor_,4)
print(splits)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
(tensor([0, 1, 2, 3]), tensor([4, 5, 6, 7]), tensor([8, 9]))


In [29]:
# 텐서 연결 : cat()
a=torch.ones(3)
print(a)
b=torch.zeros(2)
print(b)

# 연결
c=torch.cat([a,b], axis=0)
print(c)


tensor([1., 1., 1.])
tensor([0., 0.])
tensor([1., 1., 1., 0., 0.])


In [33]:
# 텐서 쌓기 : stack()
a=torch.ones(3)
b=torch.zeros(3)
s=torch.stack([a,b],axis=0)
s1=torch.stack([a,b], axis=1)
print(s1)
print(s)

tensor([[1., 0.],
        [1., 0.],
        [1., 0.]])
tensor([[1., 1., 1.],
        [0., 0., 0.]])
