In [3]:
# 텐서 생성 
import torch
import numpy as np

# 넘파이 환경 설정 : 소수점 3자리까지 표시
np.set_printoptions(precision=3)

# 리스트 생성 
a = [1,2,3]

# array 생성
b = np.array([4,5,6], dtype=np.int32)

# 리스트 -> 텐서
t_a=torch.tensor(a)
print(t_a) #벡터
print(t_a.dtype)

# array => tensor 
t_b=torch.from_numpy(b)
print(t_b)


tensor([1, 2, 3])
torch.int64
tensor([4, 5, 6], dtype=torch.int32)


In [5]:
# tensor create : one
t_ones=torch.ones(2,3) #2row x 3 col : matrix
print(f'shape : {t_ones.shape}')
print(t_ones)

shape : torch.Size([2, 3])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [6]:
# zero
t_zeros=torch.zeros(2,3)
print(t_zeros)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
