In [1]:
# torch.to() : 텐서를 다른 장치나 데이터 타입으로 이동
import torch

tensor_=torch.tensor([1,2,3])
print(tensor_) #dram (주기억 장치)
tensor_gpu = tensor_.to('cuda') #cpu vram 로 이동 
print(tensor_gpu)

# 데이터 타입 변경
tensor_float=tensor_.to(torch.float32)
print(tensor_float)

ModuleNotFoundError: No module named 'torch'

In [ ]:
# 텐서 크기와 차원 추가 , 삭제 
# 전치 : transpose()
t=torch.rand(3,5)
print(t)
# t_tr=torch.transpose(t,0,1) # 
t_tr=t.transpose(0,1)
print(t.shape ,'->', t_tr.shape)


NameError: name 'torch' is not defined

In [ ]:
# 탠서 크기 변경 : reshape
t=torch.zeros(30) #1차원 : 10
print(t)
# 2차원 변경 : 5,6
t_reshape=t.reshape(5,6)
print(t_reshape.shape)

NameError: name 'torch' is not defined

In [ ]:
# 불필요한 차원삭재 : wqueeze 
t=torch.zeros(1,2,1,4,1) #5차원
print(t.shape)
t_sqz=t.squeeze(2)
print(t_sqz.shape)

In [ ]:
#차원 추가 : unsqueeze
import numpy as np
t=torch.tensor([1,2,3])
print(t.shape) 
print(t)

# 차원추가 
u_t=t.unsqueeze(0) #0번째 차원 추가
print(u_t.shape) #2차원 된다 
print(u_t)


t_n=np.array([1,2,3])
print(t_n.shape)

In [ ]:
# element -wise : 원소별 곱셈 
# 원소별 곱셈
torch.manual_seed(1)
t1=2*torch.rand(5,2)-1
print(t1)
t2=torch.normal(mean=0, std=1, size=(5,2))
print(t2)
t3=torch.multiply(t1,t2)
print(t2)

tensor([[ 0.5153, -0.4414],
        [-0.1939,  0.4694],
        [-0.9414,  0.5997],
        [-0.2057,  0.5087],
        [ 0.1390, -0.1224]])
tensor([[ 0.8590,  0.7056],
        [-0.3406, -1.2720],
        [-1.1948,  0.0250],
        [-0.7627,  1.3969],
        [-0.3245,  0.2879]])
tensor([[ 0.8590,  0.7056],
        [-0.3406, -1.2720],
        [-1.1948,  0.0250],
        [-0.7627,  1.3969],
        [-0.3245,  0.2879]])


In [ ]:
print(t1)
# print(torch.mean(t1,axis=0)) #위에서 아래로 평균을 구하라
print(torch.mean(t1,axis=1)) #왼쪽에서 오른쪽으로 평균을 구하라


tensor([[ 0.5153, -0.4414],
        [-0.1939,  0.4694],
        [-0.9414,  0.5997],
        [-0.2057,  0.5087],
        [ 0.1390, -0.1224]])
tensor([ 0.0369,  0.1378, -0.1709,  0.1515,  0.0083])


In [ ]:
# 행렬 곱 : dot product (내적)
tt=torch.tensor([1,2,3,4,5]).to(torch.float32)
# t5 = torch.matmul(tt, torch.transpose(t1,0,1))
t5 = torch.matmul(tt, t1) #tt : 데이터, t1 : w
print(t5)

tensor([-2.8246,  3.7193])


In [ ]:
# 텐서의 노즐 연산 : 텐서의 크기 (길이 ) 계산
print(t1)
norm_t1=torch.linalg.norm(t1, ord=2, dim=1) #ord=2 유클리드 노름 
print(norm_t1)

NameError: name 't1' is not defined

In [3]:
# 텐서를 나누고, 쌓거나 연결하는 함수 
# chunk(): 텐서 특정 개수로 나누기
torch.manual_seed(1)

# 난수 생성 6개
t=torch.rand(6)
print(t)
# 특정개수 3개로 나누기 
t_c=torch.chunk(t, 3)
print(t_c)


NameError: name 'torch' is not defined

In [4]:
# split(): 텐서 튻정 크기로 나누기: reshape과 비슷하다 
torch.manual_seed(1)
t=torch.rand(5)
print(t)
t_s=torch.split(t, split_size_or_sections=[2,3])
print(t_s)


NameError: name 'torch' is not defined

In [ ]:
tensor_=torch.arange(10)
print(tensor_)
splits=torch.split(tensor_,4)
print(splits)

In [5]:
# 텐서 연결 : cat()
A=torch.ones(3)
print(a)
B=torch.zeros(2)
print(b)

# 연결 
c=torch.cat([a,b], axis=0)
print(c)

NameError: name 'torch' is not defined

In [ ]:
 # 텐서 쌓기 : stack()
a=torch.ones(3)
b=torch.zeros(3)
c=torch.stack([a,b],axis=0)
s1=torch.stack([a,b], axis=1)
print(s1)
print(s)


In [ ]:
# 이미지 